In [2]:
import numpy as np
import torch

## Different Tensors in numpy


In [4]:
# 1D
a_np = np.array([5,7,3,2,1,4])

# 2D
b_np = np.array([[4, 3, 5, 3, 5],
                 [8, 2, 6, 2, 3]])

# 3D
c_np = np.array([[[1, 5, 5, 5], [5, 2, 3, 4]],
                 [[9, 3, 6, 2], [7, 8, 2, 4]]])

print(a_np.shape, b_np.shape, c_np.shape)

(6,) (2, 5) (2, 2, 4)


## Tensors in Pytorch

In [5]:
# 1D
a_t = torch.tensor([5,7,3,2,1,4])

# 2D
b_t = torch.tensor([[4, 3, 5, 3, 5],
                    [8, 2, 6, 2, 3]])

# 3D
c_t = torch.tensor([[[1, 5, 5, 5], [5, 2, 3, 4]],
                    [[9, 3, 6, 2], [7, 8, 2, 4]]])

print(a_t.shape, b_t.shape, c_t.shape)

torch.Size([6]) torch.Size([2, 5]) torch.Size([2, 2, 4])


##Basic Operations: Element-wise addition, subtraction, multiplication, and division.

### using pytorch

In [8]:
x = torch.tensor([5, 2, 4])
y = torch.tensor([4, 8, 4])

add = torch.add(x, y)
sub = torch.sub(x, y)
mul = torch.mul(x, y)
div = torch.div(x, y)

print(add, sub, mul, div)

tensor([ 9, 10,  8]) tensor([ 1, -6,  0]) tensor([20, 16, 16]) tensor([1.2500, 0.2500, 1.0000])


### using numpy

In [9]:
x_np = np.array([5, 2, 4])
y_np = np.array([4, 8, 4])

print(x_np + y_np)
print(x_np - y_np)
print(x_np * y_np)
print(x_np / y_np)

[ 9 10  8]
[ 1 -6  0]
[20 16 16]
[1.25 0.25 1.  ]


## DOT product

### using pytorch


In [10]:
x = torch.tensor([5, 2, 4])
y = torch.tensor([4, 8, 4])

dot = torch.dot(x, y)
print(dot)

tensor(52)


### using numpy


In [11]:
x_np = np.array([5, 2, 4])
y_np = np.array([4, 8, 4])

np.dot(x_np, y_np)

np.int64(52)

## Matrix Multiplication

### using pytorch

In [12]:
A = torch.tensor([[5, 7],
                  [4, 8]])
B = torch.tensor([[2, 7],
                  [3, 5]])

matmul1 = torch.matmul(A, B)
#OR
matmul2 = A @ B

print(matmul1)
print(matmul2)

tensor([[31, 70],
        [32, 68]])
tensor([[31, 70],
        [32, 68]])


### using numpy

In [13]:
x_np = np.array([[4, 3],
                 [8, 2]])
y_np = np.array([[1, 5],
                 [5, 2]])

np.matmul(x_np, y_np)

array([[19, 26],
       [18, 44]])

## slicing, extracting subtensors using pytorch

In [14]:
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(t[0])
print(t[:, 1])
print(t[1, 2])

tensor([10, 20, 30])
tensor([20, 50])
tensor(60)


## slicing, extracting subtensors using pytorch

In [18]:
t = np.array([[10, 20, 30],
                  [40, 50, 60]])

print(t[0])
print(t[:, 1])
print(t[1, 2])

[10 20 30]
[20 50]
60


## Boolean masking using pytorch

In [15]:
t = torch.tensor([1, 2, 3, 4, 5])

mask = t > 3
filtered = t[mask]

print(filtered)

tensor([4, 5])


## Boolean masking using numpy

In [17]:
t = np.array([1, 2, 3, 4, 5])
t[t > 3]

array([4, 5])

## view in pytorch

In [21]:
x = torch.tensor([1, 2, 3, 4, 5, 6])

x_view = x.view(2, 3)
print(x_view)

tensor([[1, 2, 3],
        [4, 5, 6]])


## reshape in pytorch

In [22]:
x_reshape = x.reshape(3, 2)
print(x_reshape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


## squeeze in pytorch

In [23]:
x = torch.tensor([[1, 2, 3]])

print(x.shape)
print(x.squeeze().shape)

torch.Size([1, 3])
torch.Size([3])


## unsqueeze in pytorch

In [24]:
x = torch.tensor([1, 2, 3])

print(x.shape)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


## reshape in numpy

In [25]:
x_np =np.array([1, 2, 3, 4, 5, 6])
x_np.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

## Brodcasting in pytorch

In [26]:

x = torch.tensor([[5, 2, 8],
                  [3, 5, 2]])

y = torch.tensor([10, 90, 30])

result = x + y
print(result)

tensor([[15, 92, 38],
        [13, 95, 32]])


## Brodcasting in numpy

In [27]:
x_np = np.array([[5, 2, 8],
                  [3, 5, 2]])
y_np = np.array([10, 90, 30])

print(x_np + y_np)

[[15 92 38]
 [13 95 32]]


## out-of-place operation in pytorch


In [29]:
x = torch.tensor([5, 7, 8])
y = x + 1

print(x)
print(y)

tensor([5, 7, 8])
tensor([6, 8, 9])


## in-place opearion in pytorch

In [31]:
x = torch.tensor([6, 3, 5])
x.add_(1)

print(x)

tensor([7, 4, 6])


##out-of-place operation in numpy

In [32]:
arr = np.array([1, 2, 3, 4, 5])
arr_y = arr + 10

print(arr)
print(arr_y)

[1 2 3 4 5]
[11 12 13 14 15]


## in-place operation in numpy


In [33]:
arr = np.array([1, 2, 3, 4, 5])
arr += 10
print(arr)

[11 12 13 14 15]
